name: CI

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  test:
    strategy:
      matrix:
        html_parser: [floki, meeseeks]
        version:
          - otp: 25.0
            elixir: 1.14
            os: ubuntu-latest
          - otp: 23.0
            elixir: 1.11
            # It's necessary to run on ubuntu 20.04 for OTP 20 - 23
            # See https://github.com/erlef/setup-beam
            os: ubuntu-20.04

    runs-on: ${{ matrix.version.os }}
    name: OTP ${{matrix.version.otp}} / Elixir ${{matrix.version.elixir}} / ${{matrix.html_parser}}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.version.otp}}
          elixir-version: ${{matrix.version.elixir}}
      - run: mix deps.get
      - run: MIX_ENV=test mix compile
      - run: HTML_PARSER=${{matrix.html_parser}} mix test
      - run: MIX_ENV=test mix credo --strict
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    name: Deploy published release
    env:
      HEX_API_KEY: ${{secrets.HEX_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0
          elixir-version: 1.14
      - run: mix deps.get
      - run: mix hex.publish --yes
